export const reservedPropKeys = [
  "token",
  "ip",
  "$bucket / bucket",
  "$distinct_id / distinct_id",
  "$device_id",
  "$user_id",
  "$event_name",
  "$time / time",
  "$insert_id",
  "$identified_id",
  "$anon_id",
  "alias",
  "$distinct_ids",
  "$distinct_id_before_identity",
  "$is_reshuffled",
  "$failure_description",
  "$failure_reason",
  "$identity_failure_reason",
  "mp_original_distinct_id",
  "mp_original_event_name",
  "$source",
  "$partner_id",
  "$warehouse_type",
  "$warehouse_import_id",
  "$warehouse_import_job_id",
  "$warehouse_import_run_id",
  "$duration_s",
  "$event_count",
  "$origin_start",
  "$origin_end",
];
